$(function(){
  $(".depth0").click(function(){
    if($(this).fine(".depth").has(".active")){
      $(this).fine(".depth").addClass("active")
      $(this).fine(".depth").removeClass("active");
    }else{
        $(this).fine(".depth").addClass("active")
    }
    $(this).toggle();
  });
});
